### PR TITLE
Fix log2 calculation

### PR DESCRIPTION
**Pull request by nqtronix**
I think I have found another issue, the log2 implementaion is not correct. The issue is best shown with examples:

```
1: log2(0b0001) = 0; clz(0b0001) = 31
2: log2(0b0010) = 1; clz(0b0010) = 30
4: log2(0b0100) = 2; clz(0b0100) = 29
8: log2(0b1000) = 3; clz(0b1000) = 28
```

This means the formula must be `log2(x) = 31 - clz(x)`

---

If you use this fixed formula, the calculation for the bit index is also correct. This is easy to see if we fill in example values:

formula: `p2 = p1 - log2uint8(p1) - 2;`  <=> `p2 = p1 - (31-clz(p1)) - 2;`

bit 0 flipped -> index 3 = 0b0011: `3 - (31-clz(0b0011)) - 2` = `3 - (31-30) - 2` = 0
bit 1 flipped -> index 5 = 0b0101: `5 - (31-clz(0b0101)) - 2` = `5 - (31-29) - 2` = 1
bit 2 flipped -> index 6 = 0b0110: `6 - (31-clz(0b0110)) - 2` = `6 - (31-29) - 2` = 2
bit 3 flipped -> index 7 = 0b0111: `7 - (31-clz(0b0111)) - 2` = `7 - (31-29) - 2` = 3
bit 4 flipped -> index 9 = 0b1001: `9 - (31-clz(0b1001)) - 2` = `9 - (31-28) - 2` = 4

I did not verify the alternative path (#ifdef 0)

### CODE REVIEW

**Comment by BenBE** [comment]
Will have to recheck this, but given the other (builtin-free) implementation below, this seems intentional.

**Comment by BenBE** [comment]
Looking at the place where this is used (in the decoder when there's an error) there seems to be some overall misalignment, when this is simply changed. Still looking into the details, but I'm on it …

**Comment by nqtronix** [comment]
No rush. I've written my own implementation that can handle different sizes other then (127,120) and while compared it to your implementation I noticed this differnece. I have to admit that I did not test the proposal together with the rest of your code as mine works and the calculations were very similiar.

Over the weekend I can port my test cases to your code and proove the proposal. (Didn't do so yet because I'm short on time, but I still wanted to let you know any errors I founds, kinda as a thank you for making your code open source)

**Comment by BenBE** [comment]
Having some (automated) test cases sure would be great.

As far as my investigation on this issue goes, the proposed patch is incomplete, as the decoder [in this line](https://github.com/BenBE/FastHamming/blob/b290c97ae8d143d5f457425dc6889a47a43e20f5/fast_hamming.c#L179) assumes the first data bit to be bit index 3.

So the first few bits effectively are:
```
0 -> Overall message parity
1 -> Bit 0 parity
2 -> Bit 1 parity
3 -> 1st user data bit (byte 0, Bit 0)
4 -> Bit 2 parity
5 -> 2nd user data bit (byte 0, bit 1)
6 -> 3rd user data bit (byte 0, bit 2)
7 -> 4th user data bit (byte 0, bit 3)
8 -> Bit 3 parity
…
126 -> 119th user data bit (byte 14, bit 6)
127 -> 120th/last user data bit (byte 14, bit 7)
```

When decoding the linked calculation basically retrieves the user data offset (byte and bit address) by subtracting the number of parity bits that have already been passed at that point. Thus 3 must be translated back to 0, 5 to 1, 6 to 2, 7 to 3, 9 to 4, and so on. Indices 4, 8 and 16 are handled differently and don't affect that particular line. See comments around the linked place in the code.

AFAIC it seems likely that to change the `log2uint8` behavior the linked line needs to be fixed too; changing the `- 2` into `- 3`.

**Comment by nqtronix** [comment]
I've pushed some basic test code to my repo: https://github.com/nqtronix/FastHamming

This code was build in ATMEL Studio and runs on a SAML21 MCU with a debugger attached. The `asm("nop")` is used to set a breakpoint, once it is hit, the variable values can be inspected. `volatile` is needed for the result, otherwise the compiler opimizes it away. You will have to adopt the code for your STM MCU and programming enviroment.

Currently the code fails with `(FAST_HAMMING_ERR_DATA | FAST_HAMMING_ERR_DATA_RES | FAST_HAMMING_ERR_CODE | FAST_HAMMING_ERR_CODE_RES | FAST_HAMMING_ERR_PARITY | FAST_HAMMING_ERR_DOUBLE)` with both the old and new log2 calculation. I think it's likely that I've interpreted the parameter list wrong, please check that first (and provide a description in the header file).

**Comment by BenBE** [comment]
Having a closer look at the issue I found that only the case using the `__builtin_clz` variant of the code was affected by the off-by-one issue.

Also in the end I decided against using your patches for this particular issue, as pulling them in was more complicated than using what I already had locally from experimenting.

Also note that this repository uses AGPLv3 for its license. Thus please strip down your proposed additional tests in such a way to avoid the Apache licensed parts that the Atmel Studio project would introduce. The best way to do this is by following the example tests I've included with the latest batch of patches.

**Comment by nqtronix** [comment]
>Also note that this repository uses AGPLv3 for its license.

I did not mean to violate your license. As I said before I wrote a hamming code implementation from scratch and only used your code to compare it against. The test file was derived from my code as a quick example, but you are free to use your own. I deleted my fork in order to resolve the licensing issue.

**Comment by BenBE** [comment]
I didn't say that there was any violation. I just wanted to point out and caution, that Apache != AGPL and thus integrating the code (while possible AFAIK) would not have been ideal. Things are much easier license-wise, when things agree. :wink: Also I'd have been much more explicit, if I believed there was any active violation.

PS: Can you open a new PR with just the (minimal) tests you wrote? Any `.c` file inside the `test/` folder is automatically picked up. Have a look at the two existing ones for a small example.

**Comment by nqtronix** [comment]
Honestly I don't wanna deal with all the issues surrounding licensing. As long as people don't claim my work as theirs and as long as they don't try to hold me liable for anything they do with the code, they can do whatever the fuck they want. Because your repo is licensed under a GPL variant, I don't want to deal with it's restrictions, so I won't use it and therefore it makes no sense to put in more effort beyond fixing small things. 

My tests were quite simple: Generate correct encoded data, then in a for loop destroy one bit at a time and let the algorithm fix it. Finally destroy two bits and see if the algorithm reports correctly that the data can't be recovered. I've attached the two relevant files. It says "MIT license" so that I am on the legally safe side, but as I stated before, I don't really care what you do with it.

[FastHammingTest.zip](https://github.com/BenBE/FastHamming/files/6950481/FastHammingTest.zip)

**Pull request closed without merging**
